"""
Doc Agent - Phase 4
Synchronizes technical documentation from code changes, commit history, and PR descriptions.
"""

import re
import textwrap
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

from ..core.base_agent import BaseAgent
from ..core.models import RefactorProposal, DocUpdate


SYSTEM_PROMPT = """You are a technical writer who produces clear, accurate developer documentation.
Given code changes and context, generate or update:
- Function/class docstrings (Google style)
- API reference entries (OpenAPI-compatible descriptions)
- Changelog entries (Keep a Changelog format)
- README sections

Be concise. Avoid marketing language. Use active voice. Output Markdown."""


@dataclass
class DocConfig:
    docs_root: str = "docs"
    api_docs_dir: str = "docs/api"
    changelog_file: str = "CHANGELOG.md"
    readme_file: str = "README.md"
    auto_update_changelog: bool = True
    auto_update_api_docs: bool = True
    style: str = "google"  # google | numpy | sphinx


class DocAgent(BaseAgent):
    """
    Documentation synchronization agent.

    Pulls context from:
    - Code comments and existing docstrings
    - Refactoring proposals (what changed and why)
    - Git commit messages and PR descriptions
    - Existing documentation structure

    Produces:
    - Updated API reference pages
    - Changelog entries
    - Inline docstring improvements
    """

    AGENT_NAME = "doc_agent"
    VERSION = "0.2.1"

    def __init__(self, config: DocConfig, llm_client=None):
        super().__init__(llm_client=llm_client)
        self.config = config
        self.updates: list[DocUpdate] = []

    def run(self, proposals: list[RefactorProposal], version: str = "Unreleased") -> list[DocUpdate]:
        """Generate documentation updates from refactoring proposals."""
        self.logger.info(f"[DocAgent] Processing {len(proposals)} proposals for doc sync")

        if self.config.auto_update_api_docs:
            for proposal in proposals:
                for change in proposal.changes:
                    if change.get("file", "").endswith(".py"):
                        update = self._generate_api_doc_update(proposal, change)
                        if update:
                            self.updates.append(update)

        if self.config.auto_update_changelog:
            changelog_update = self._generate_changelog_entry(proposals, version)
            if changelog_update:
                self.updates.append(changelog_update)
                self._prepend_changelog(changelog_update)

        self.logger.info(f"[DocAgent] Generated {len(self.updates)} doc updates")
        return self.updates

    def _generate_api_doc_update(
        self, proposal: RefactorProposal, change: dict
    ) -> Optional[DocUpdate]:
        """Generate API reference update for a changed file."""
        file_path = Path(change["file"])
        module_name = file_path.stem
        doc_path = Path(self.config.api_docs_dir) / f"{module_name}.md"

        if self.llm_client:
            content = self._llm_generate_api_doc(proposal, change)
        else:
            content = self._template_api_doc(module_name, change)

        if not content:
            return None

        doc_path.parent.mkdir(parents=True, exist_ok=True)
        doc_path.write_text(content, encoding="utf-8")

        return DocUpdate(
            doc_type="api_reference",
            file=str(doc_path),
            content=content,
            source_proposal=proposal.title,
        )

    def _llm_generate_api_doc(self, proposal: RefactorProposal, change: dict) -> str:
        prompt = f"""Generate API documentation for the following code change:

Proposal: {proposal.title}
File: {change['file']}

Before:
```python
{change.get('original', '# (not available)')}
```

After:
```python
{change.get('replacement', '# (not available)')}
```

Explanation: {change.get('explanation', '')}

Produce a Markdown API reference section including:
- Function signature
- Parameter descriptions
- Return value
- Example usage
- Any important notes about the change"""

        return self.llm_client.chat(
            system=SYSTEM_PROMPT,
            user=prompt,
            temperature=0.3,
        )

    def _template_api_doc(self, module_name: str, change: dict) -> str:
        return textwrap.dedent(f"""
            # `{module_name}`

            > Auto-generated by DocAgent. Last updated: {datetime.now().strftime('%Y-%m-%d')}.

            ## Changed Function

            **File:** `{change['file']}`
            **Line:** {change.get('line', 'N/A')}

            ### Description

            {change.get('explanation', 'No explanation provided.')}

            ### Before

            ```python
            {change.get('original', '# not available')}
            ```

            ### After

            ```python
            {change.get('replacement', '# not available')}
            ```
        """).strip()

    def _generate_changelog_entry(
        self, proposals: list[RefactorProposal], version: str
    ) -> Optional[DocUpdate]:
        """Generate a changelog entry in Keep a Changelog format."""
        if not proposals:
            return None

        date_str = datetime.now().strftime("%Y-%m-%d")
        lines = [f"## [{version}] - {date_str}\n"]

        security_fixes = [p for p in proposals if any(
            i.category == "security" for i in p.source_issues
        )]
        perf_fixes = [p for p in proposals if any(
            i.category == "performance" for i in p.source_issues
        )]
        debt_fixes = [p for p in proposals if any(
            i.category == "tech_debt" for i in p.source_issues
        )]

        if security_fixes:
            lines.append("### Security\n")
            for p in security_fixes:
                lines.append(f"- {p.title}\n")

        if perf_fixes:
            lines.append("\n### Performance\n")
            for p in perf_fixes:
                lines.append(f"- {p.title}\n")

        if debt_fixes:
            lines.append("\n### Refactored\n")
            for p in debt_fixes:
                lines.append(f"- {p.title}\n")

        content = "".join(lines)
        return DocUpdate(
            doc_type="changelog",
            file=self.config.changelog_file,
            content=content,
            source_proposal=f"{len(proposals)} proposals",
        )

    def _prepend_changelog(self, update: DocUpdate) -> None:
        """Insert new changelog entry at the top of CHANGELOG.md."""
        changelog = Path(update.file)
        if changelog.exists():
            existing = changelog.read_text(encoding="utf-8")
            # Insert after the first H1 heading if present
            match = re.search(r"^# .+\n", existing, re.MULTILINE)
            if match:
                insert_pos = match.end()
                new_content = existing[:insert_pos] + "\n" + update.content + "\n" + existing[insert_pos:]
            else:
                new_content = update.content + "\n\n" + existing
        else:
            new_content = "# Changelog\n\nAll notable changes to this project will be documented here.\n\n" + update.content
        changelog.parent.mkdir(parents=True, exist_ok=True)
        changelog.write_text(new_content, encoding="utf-8")
        self.logger.info(f"[DocAgent] Updated changelog: {changelog}")
